-- DATABASE CREATION SECTION
use master
IF EXISTS (SELECT * FROM sys.databases WHERE NAME= 'SMSDB')
DROP DATABASE SMSDB
CREATE DATABASE SMSDB
use SMSDB

-- TABLE CREATION SECTION
CREATE TABLE Student(
	StudentID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[Name] VARCHAR (20) NOT NULL,
	Surname VARCHAR (MAX) NOT NULL,
	STnumber VARCHAR (150) UNIQUE NOT NULL
);

CREATE TABLE Module(
	ModuleID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Code VARCHAR (8) NOT NULL,
	[Name] VARCHAR (150) NOT NULL
);

CREATE TABLE Enrollment(
	EnrollmentID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	StudentID INT FOREIGN KEY REFERENCES Student(StudentID) NOT NULL,
	ModuleID INT FOREIGN KEY REFERENCES Module(ModuleID) NOT NULL,
	[Status] VARCHAR (60) NOT NULL,
	Semester INT NOT NULL

);

-- TABLE INSERTION SECTION
INSERT INTO Student ([Name], Surname, STnumber)
VALUES ('Samkelo', 'Molefi', 'ST10292723')

INSERT INTO Module (Code, [Name])
VALUES ('CLDV6212', 'Cloud Development')

INSERT INTO Enrollment (StudentID, ModuleID, [Status], Semester)
VALUES (1, 1, 'Pending', '3')


	--/-- TABLE ALTERATION SECTION

-- TABLE MANIPULATION SECTION
SELECT * FROM Student

SELECT * FROM Module

SELECT * FROM Enrollment

-- STORED PROCEDURES 